name: Bug Report
description: Report a defect or regression
title: "[Bug] "
labels:
  - type:bug
body:
  - type: markdown
    attributes:
      value: |
        Please include enough detail to reproduce reliably.

  - type: dropdown
    id: owner_role
    attributes:
      label: Intended owner role
      options:
        - implementer
        - verifier
        - operator
        - reviewer
        - planner
    validations:
      required: true

  - type: dropdown
    id: risk_level
    attributes:
      label: Risk classification
      options:
        - low
        - medium
        - high
    validations:
      required: true

  - type: input
    id: route
    attributes:
      label: Affected route/page
      placeholder: /shop, /blog/some-slug, /admin/content/media
    validations:
      required: true

  - type: dropdown
    id: environment_profile
    attributes:
      label: Environment profile
      options:
        - dev
        - prod
        - dev-sandbox
    validations:
      required: true

  - type: dropdown
    id: payments_mode
    attributes:
      label: Payments provider mode
      options:
        - mock
        - real (sandbox)
        - real (live)
        - not related
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: List exact steps and inputs.
    validations:
      required: true

  - type: textarea
    id: evidence_expected
    attributes:
      label: Expected evidence artifacts
      description: Which logs/tests/workflow artifacts should confirm the fix?
      placeholder: artifacts/audit-evidence/*, backend test output, compose-smoke run URL
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Add measurable pass conditions.
    validations:
      required: true

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics/logs/screenshots
      description: Include request IDs, console errors, and relevant logs.
