name: Bug Report
description: Report a defect or regression
title: "[Bug] "
labels:
  - type:bug
body:
  - type: markdown
    attributes:
      value: |
        Please include enough detail to reproduce reliably.

  - type: dropdown
    id: risk
    attributes:
      label: Risk level
      options:
        - low
        - medium
        - high
    validations:
      required: true

  - type: input
    id: route
    attributes:
      label: Affected route/page
      placeholder: /shop, /blog/some-slug, /admin/content/media
    validations:
      required: true

  - type: dropdown
    id: environment_profile
    attributes:
      label: Environment profile
      options:
        - dev
        - prod
        - dev-sandbox
    validations:
      required: true

  - type: dropdown
    id: payments_mode
    attributes:
      label: Payments provider mode
      options:
        - mock
        - real (sandbox)
        - real (live)
        - not related
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: List exact steps and inputs.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics/logs/screenshots
      description: Include request IDs, console errors, and relevant logs.
    validations:
      required: true

  - type: textarea
    id: evidence_commands
    attributes:
      label: Evidence command list
      value: |
        make verify
    validations:
      required: true
