name: Feature Request
description: Propose a feature or enhancement
title: "[Feature] "
labels:
  - type:feature
body:
  - type: dropdown
    id: owner_role
    attributes:
      label: Intended owner role
      options:
        - planner
        - implementer
        - verifier
        - operator
        - reviewer
    validations:
      required: true

  - type: dropdown
    id: risk_level
    attributes:
      label: Risk classification
      options:
        - low
        - medium
        - high
    validations:
      required: true

  - type: input
    id: objective
    attributes:
      label: Objective
      placeholder: What user outcome should this enable?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
      description: Describe the change at product and technical level.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope boundaries
      description: Explicitly list in-scope and out-of-scope.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Add measurable criteria.
    validations:
      required: true

  - type: textarea
    id: evidence_expected
    attributes:
      label: Expected evidence artifacts
      description: Which tests/workflow artifacts must exist before merge?
      placeholder: frontend build output, backend pytest, audit-evidence artifact paths
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Primary area
      options:
        - backend
        - frontend
        - infra
        - ci
        - docs
        - payments
        - seo
        - dam
    validations:
      required: true
