name: Feature Request
description: Propose a feature or enhancement
title: "[Feature] "
labels:
  - type:feature
body:
  - type: input
    id: objective
    attributes:
      label: Objective
      placeholder: What user outcome should this enable?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
      description: Describe the change at product and technical level.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Add measurable criteria.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Primary area
      options:
        - backend
        - frontend
        - infra
        - ci
        - docs
        - payments
        - seo
        - dam
    validations:
      required: true
