import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function parseDotEnv(contents) {
  const result = {};
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2)
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function firstExisting(paths) {
  for (const candidate of paths) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(scriptsDir, '..');
const envPath = firstExisting([
  path.join(frontendRoot, '.env'),
  path.join(frontendRoot, '.env.local'),
  path.join(frontendRoot, '.env.example')
]);

const parsed = envPath ? parseDotEnv(fs.readFileSync(envPath, 'utf8')) : {};

const apiBaseUrl = process.env.API_BASE_URL ?? parsed.API_BASE_URL ?? '/api/v1';
const appEnv = process.env.APP_ENV ?? parsed.APP_ENV ?? 'development';
const stripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY ?? parsed.STRIPE_PUBLISHABLE_KEY ?? '';
const sentryDsn = process.env.SENTRY_DSN ?? parsed.SENTRY_DSN ?? '';

const outPath = path.join(frontendRoot, 'src', 'assets', 'app-config.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });

const config = { apiBaseUrl, appEnv, stripePublishableKey, sentryDsn };
const payload = `// Auto-generated by scripts/generate-config.mjs\nwindow.__APP_CONFIG__ = ${JSON.stringify(config, null, 2)};\n`;

fs.writeFileSync(outPath, payload, 'utf8');
console.log(`Wrote ${path.relative(frontendRoot, outPath)} from ${envPath ? path.relative(frontendRoot, envPath) : 'defaults'}`);
